version: '3.7'

services:

  react-prod:
    container_name: react-prod
    build:
      context: ./client/react/
      dockerfile: Dockerfile
    ports:
      - '1337:80'
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: "flask"
      POSTGRES_USER: "flask"
      POSTGRES_DB: "flaskdb"
    ports:
      - 5432:5432
  